### ISSUE TITLE
proof-reading errors found on Intro page

### ISSUE THREAD

**Issue by beverlyvoth** [proofgeist/SimpleQ#14]
https://simpleq.proofgeist.com/docs/intro
(found typo "dded" should be "added"):
### MESSAGES
	* -
{
  "Event":"A JSON string indicating the type of event, e.g. 'Schedule Change'",
  "Student_ID":"A JSON string containing the external identifier for the Student.",
  "Dropped":"A JSON array containing the identifier for each class that was Dropped",
  "Added":"A JSON array containing the identifier for each class that was dded"
}
	* +
{
  "Event":"A JSON string indicating the type of event, e.g. 'Schedule Change'",
  "Student_ID":"A JSON string containing the external identifier for the Student.",
  "Dropped":"A JSON array containing the identifier for each class that was Dropped",
  "Added":"A JSON array containing the identifier for each class that was added"
}

**Comment by beverlyvoth** [comment]
Same page:
### What is a Subscriber?
	Q: (on the image) does the Subscriber Key not need to follow the same dot notation as the Channel? If not, why, or perhaps more explanation on the naming convention here for subscribers.

**Comment by toddgeist** [comment]
It does not need to follow the same notation.  It is just a unique string.  Dot notation for channels, will be important in the future.

Fixed the typo

**Comment by beverlyvoth** [comment]
Thanks, @toddgeist ! 
I'll keep going on comments, if you think it will help. Totally ignore if not relevant. I'm just reading as a new user (putting on my Tech Editor hat here. LOL), so I think these *might* be stumbling blocks for others.
Bev
