### ISSUE TITLE
Queue's fail every time, until I 'retry' when they work fine?

### ISSUE THREAD

**Issue by glenavontechnology** [proofgeist/SimpleQ#19]
All payloads, including the test payload sent via the 'Test Webhook' button from within SimpleQ fail straight away with this error:

{"messages":[{"code":100,"message":" Error performing script \"\" in script \"deliver staticDSN message ( message ; listener )\" at #deliver message via script call"}]}

As soon as I press 'RETRY" from within the Queue the payload is sent (and received) fine?!

**Comment by glenavontechnology** [comment]
Have checked the External Data Source name, all looks good to me...

**Comment by glenavontechnology** [comment]
Thought it might have been an Underscore in the Filename, but that's not it...

**Comment by toddgeist** [comment]
Error code 100 means that the file is missing from the perspective of the script that is trying to open it. In this case, the Script that is calling it is doing so through a Server Side Scheduled Script.

So what is different about the perspective of a Server Side Script vs a script called by pressing a button in the UI? Here are a couple of things to check.

1. Privileges. Check the username and password for that scheduled script.  Does it exist in all the other files?
2. Server Side Scripts are running in a virtual client that has been opened "As Host".  When a client is running "As Host", it's external file references work differently than when it is opened hosted off a server.  This doesn't matter normally if all the files in question are placed in the same folder on the server.  But if they are in different folders, then the file reference will have to include the relative path between them, just like what would happen if you are running files locally on your desktop.  So is SimpleQ in a different folder on the server from the other files?

Todd

**Comment by glenavontechnology** [comment]
Hmmm, interesting. The SimpleQ file is in the same (default) folder as the Target file, I'm interested in the creds for the scheduled script though - do you mean that I have to have the same username:password combo setup in SimpleQ AND in my target file?

**Comment by toddgeist** [comment]
Yup.

The server-side script gets called with a username:password.  SimpleQ and all other files that SimpleQ talks to will need that same username:password combo.

**Comment by glenavontechnology** [comment]
Boom. Got there in the end. I'm getting so used to authenticating via REST API's that I'd kinda forgotten then nuances of Filemaker's External Data Sources config! Thanks Todd, this is great.

**Comment by toddgeist** [comment]
Yay!
